
flask:
  SECRET_KEY: "skift_mig_gerne"
  SENSOR_NAME: "EEG Electrode Test"
  SENSOR_UNIT: "mV"

database:
  host: "127.0.0.1"
  port: "5432"
  user: "postgres"
  password: "sander12"
  dbname: "hospital"  

raspberry:
  host: "192.168.30.2"   
  port: "5001"